### ISSUE TITLE
AttributeError: module 'string' has no attribute 'rstrip'

### ISSUE THREAD

**Issue by pouledodue** [portante/pycscope#37]
```
$ pycscope -V
pycscope.py: Version 1.2.1
```
```
$ python -V
Python 3.7.3
```
```
pycscope -i ./cscope.files
Traceback (most recent call last):
  File "/usr/local/bin/pycscope", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pycscope/__init__.py", line 118, in main
    args.extend(list(map(string.rstrip, open(a, 'r').readlines())))
AttributeError: module 'string' has no attribute 'rstrip'
```

**Comment by idbrii** [comment]
string.lstrip doesn't exist in python 3.7. That line can be rewritten:

```args.extend([line.rstrip() for line in open(a, 'r').readlines()])```

That gets pycscope to build my cscope database but cscope database for me. Vim complains:

```
cs_read_prompt EOF: No such file or directory
E609: Cscope error: cscope: cannot read list size from file ~/talon/cscope.out
```

The database is only 236 KB and looks like a valid plain text file. I'm not sure where the error comes from.

**Comment by meenx** [comment]
Is this issue fixed? If yes, by when will this be merged ?

**Comment by xin3liang** [comment]
Any update on this issue? Still hitting this issue now when installed by pip install.

**Comment by xin3liang** [comment]
> Any update on this issue? Still hitting this issue now when installed by pip install.

But when pip install ./pycscope source code,  it doesn't encounter this issue. master already has the fixed d991da9d45c6d0a4c6617c267da238a5f1bd2bdf.
