### ISSUE TITLE
Cannot install: No module named 'parser'

### ISSUE THREAD

**Issue by ClayShoaf** [portante/pycscope#49]
When I try to install, I get the following output:
```
[user ~/github/pycscope]$ python setup.py install
Traceback (most recent call last):
  File "/home/user/github/pycscope/setup.py", line 5, in <module>
    from pycscope import __version__
  File "/home/user/github/pycscope/pycscope/__init__.py", line 25, in <module>
    import keyword, parser, symbol, token
ModuleNotFoundError: No module named 'parser'
```

**Comment by ruben2020** [comment]
I think the issue is basically that pycscope cannot be run using Python 3.10 because the parser module has been removed.

**Comment by arkdae** [comment]
That's not the only thing that is gone in 3.10, so is the symbol module.

**Comment by brianphaley** [comment]
Hi Peter!

And at least one new distro (Ubuntu 22.04) is 3.10+ only now ;-(  I guess ast is the closest replacement?  I might have to start looking at this as I use it every day, until then can generate cscope.out files on an older system.

**Comment by portante** [comment]
Any help you can offer would be great.  I have not had a chance to dive into this work for a long time now.

**Comment by ruben2020** [comment]
@portante If I have time, I'll give it a try to do some porting.

**Comment by ruben2020** [comment]
@portante The [`parser`](https://docs.python.org/3.9/library/parser.html) module has been deprecated since Python 3.10. The only way left is the [`ast`](https://docs.python.org/3.10/library/ast.html) (abstract syntax tree) module. However, I think pycscope requires a concrete syntax tree that preserves the original source code, rather than an abstract syntax tree that's lossy. So, instead of using the [`ast`](https://docs.python.org/3.10/library/ast.html) module, you may need something like [`LibCST`](https://libcst.readthedocs.io/en/latest/why_libcst.html).

**Comment by ruben2020** [comment]
@portante oh. I'm mistaken. There might be a far simpler way to fix this. Please see [this page](https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/1654/). The change looks trivial. They simply replaced `parser.suite` with `ast.parse`.

**Comment by ruben2020** [comment]
@portante I tried it, but it doesn't work. I think the old tuple structure is no longer used. Looks like you have no other choice but to port pycscope to `ast` or `LibCST`, which is a huge change to pycscope. It's almost a rewrite I expect. The other alternative is for you to get the old `parser` and `symbol` modules' source code from 3.9 and incorporate it into pycscope.

**Comment by xin3liang** [comment]
FYI, for Ubuntu users, maybe installing the older Python 3.9 as a workaround:
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.9 python3.9-venv
python3.9 -m venv ~/.venvs/py3.9
. ~/.venvs/py3.9/bin/activate
pip install ./pycscope
```
Reference: https://askubuntu.com/questions/682869/how-do-i-install-a-different-python-version-using-apt-get
